[package]
name = "rust-cpython-concurrency"
version = "0.1.0"
authors = ["Stu Hood <stuhood@gmail.com>"]
edition = "2018"

[dependencies]
cpython = "0.6"
futures = "0.3"
tokio = { version = "1.4", features = ["macros", "rt", "rt-multi-thread"] }
